name: linting, testing, buildings
on:
  push:
    branches: [main, developer]
  pull_request:
    branches: [main, developer]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: update screenshot
        run: npx loki update --reactUri="file:./storybook-static"
      - name: screenshot testing
        run: npm run test:ui:ci
